services:
  web:
    image: myacr.azurecr.io/smartscale-web:latest
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_URL=http://api:3001

    api:
    build:
      context: .
      target: api-prod
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped
